apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.repo_name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: YotpoLtd/${{ values.repo_name }}
    backstage.io/techdocs-ref: dir:.
  tags:
    - lighthouse
    - widget-v3
    - ${{ values.product_line }}
spec:
  type: widget
  lifecycle: production
  owner: ${{ values.owner }}
  system: ${{ values.system }}
