apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-perite-vuew-widget
  title: Test – Create Petite Vuew widget
  description: Create new repo for Petite Vuew widget development
  tags:
    - frontend
    - widgets
    - petite-vue
spec:
  owner: Ivys
  type: widget
  parameters:
    - title: Provide basic information
      required:
        - repo_name
        - product_line
      properties:
        repo_name:
          title: Repo name
          type: string
          description: Name of the repo to be created
          default: "widget-katya-test"
          pattern: "^widget-([a-z]+-?)+$"
        description:
          title: Repo description
          type: string
          description: Repo description
          default: "Description"
        slack_channel:
          title: Slack channel name
          type: string
          description: Slack channel for deployment alerts
          default: "dev-alerts"
        system:
          title: System
          type: string
          default: "test" # todo
        product_line:
          $yaml: ../../reusable/parameters/product_line.yaml
        owner:
          $yaml: ../../reusable/parameters/owner.yaml

    - $yaml: ../../ci/add-lighthouse-ci/steps/add-lhci-template/parameters.yaml
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          product_line: ${{ parameters.product_line }}
          repo_name: ${{ parameters.repo_name }} # widget-cool-name
          widgetName: ${{ parameters.repo_name | replace("widget", "") | replace("-", " ") | title | replace(" ", "") }} # CoolName
          widget_name: ${{ parameters.repo_name | replace("widget-", "")  }} #cool-name
          description: ${{ parameters.description }}
          system: ${{ parameters.system }}
          owner: ${{ parameters.owner | lower | replace("-admins", "") }}


    - $yaml: ../../ci/add-lighthouse-ci/steps/add-lhci-template/step.yaml
    - $yaml: ../../ci/hydrate-pr-description/steps/add-gha-template/step.yaml

    - $yaml: ../../reusable/steps/create-github-repo/step.yaml

  output:
    links:
      - url: ${{steps.publish_repo.output.remoteUrl }}
        title: "Go to freshly created repo"
      - url: https://github.com/YotpoLtd/terraform-github/tree/master/RnD-teams
        title: "Add ${{ parameters.repo_name }} to your team in terraform-github"


