apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: copy-create-cypress-project
  title: Copy Create Cypress Project
  description: Create Cypress Project for e2e tests
  tags:
    - frontend
    - cypress
    - typescript
    - testing
    - e2e
spec:
  owner: Ivys
  type: website
  parameters:
    - title: Provide some simple information
      required:
        - repo_name
        - product_line
        - product
        - project_name
      properties:
        - repo_name:
          title: Repo name
          type: string
          description: Name of the repo
        - description:
            title: Repo description
            type: string
            description: Repo description
        - $yaml: ./project_name.yaml
        - $yaml: ./product.yaml


  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          description: ${{ parameters.description }}
          repo_name: ${{ parameters.repo_name }}
          owner: ${{ parameters.owner }}
          #          owner: ${{ parameters.collaborators[0].owner }}
          slack_channel: ${{ parameters.slack_channel }}
          product_line: ${{ parameters.product_line }}
          product: ${{ parameters.product }}
          project_name: ${{ parameters.project_name }}

    - $yaml: ../../ci/hydrate-pr-description/steps/add-gha-template/step.yaml

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: [ 'github.com' ]
        description: ${{ parameters.description }}
        repoUrl: 'github.com?owner=YotpoLtd&repo=${{ parameters.repo_name }}'
        defaultBranch: master
        topics:
          - k8s

    - id: add-collaborator
      name: Add team as a collaborator
      action: http:backstage:request
      input:
        method: 'PUT'
        path: /api/proxy/github/api/orgs/YotpoLtd/teams/${{  parameters.owner  }}/repos/YotpoLtd/${{  parameters.repo_name  }}
        headers:
          content-type: 'application/json'
          accept: 'application/vnd.github.v3+json'
        body:
          permission: admin


  output:
    remoteUrl: ${{ steps.publish.output.remoteUrl }}
